categories:
  - title: 'Features'
    label: 'feature'
  - title: 'Bug Fixes'
    label: 'fix'
  - title: 'Maintenance'
    label: 'chore'

template: |
  ## What’s Changed

  $CHANGES

tag-template: v$NEXT_PATCH_VERSION
