name: Generate terraform docs
on:
  - pull_request
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Should generate USAGE.md for tf11_basic
      uses: ./
      with:
        tf_docs_working_dir: examples/tf11_basic
        tf_docs_template: |
          # Test tf11 basic

          ## Verify
          Should use the template defined instead of the default
          Should inject the table under usage

          # Usage
          <!--- BEGIN_TF_DOCS --->
          <!--- END_TF_DOCS --->

    - name: Should generate README.md for tf11_extra_args
      uses: ./
      with:
        tf_docs_working_dir: examples/tf11_extra_args
        tf_docs_output_file: README.md
        tf_docs_content_type: document
        tf_docs_indention: '3'
        tf_docs_args: '--with-aggregate-type-defaults --no-required'
        tf_docs_output_method: replace

    - name: Should generate README.md for tf12_atlantis
      uses: ./
      with:
        tf_docs_atlantis_file: atlantis.yaml
        tf_docs_output_file: README.md

    - name: Should generate README.md for tf12_find and its submodules
      uses: ./
      with:
        tf_docs_find_dir: examples/tf12_find

    - name: Should generate README.md for tf12_inject and push up all changes
      uses: ./
      with:
        tf_docs_find_dir: examples/tf12_inject
        tf_docs_output_file: README.md
        tf_docs_git_push: 'true'
        tf_docs_git_commit_message: 'terraform-docs: automated action'
